# ================================================
# Spring Boot Application
# ================================================
spring.application.name=kiosk-backend
server.port=8081

# ================================================
# COM Port Ayarları
# ================================================
comport.data.bits=8
comport.stop.bits=1
comport.parity=0
# Windows için örnek port: COM3, Linux için: /dev/ttyUSB0
comport.name=COM3
# EKB1 için 57600 , EKB2 için 19200 yazılmalı
comport.baudrate=57600

# ================================================
# Display Ayarları
# ================================================
# Display sistemini aktif/pasif yapmak için
is.displays.active=true
# Ana display sayısı (0 ise ana display mesajı gönderilmez)
main.display.count=1
# Display tipi: 1 = EKB1, 2 = EKB2
display.type=1
# Display kapanis saati
display.closingHour=16:55

# ================================================
# Logging Ayarları
# ================================================
# Log dosyası yazma yetkisi olan bir dizine yönlendirildi
logging.file.name=D:/Temp/kioskbackend/kiosk-logs.txt
logging.level.root=INFO
logging.level.org.hibernate=ERROR
# ================================================
# Branch ID
# ================================================
kiosk.branch.id=3

# ================================================
# Printer Ayarları (mm)
# ================================================
printer.paper.width=60
printer.paper.height=205