spring.application.name=qintech-api
#server.port=443
#server.port=8080

# Segment Service
remote.server.url=http://192.168.1.108:80/api/EmlakCustomer/CustomerInfo
#remote.server.url=https://segment.allintech.local/api/EmlakCustomer/CustomerInfo
#remote.server.url=http://192.168.1.108:5003/api/IsBankCustomer/Customer/
remote.server.timeout=5000

#spring.datasource.url=jdbc:sqlserver://192.168.1.114:1533;databaseName=qintech_ekb;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.url=jdbc:sqlserver://192.168.1.114:1533;databaseName=qintech_ekb_banka;encrypt=true;trustServerCertificate=true;integratedSecurity=true
#spring.datasource.url=jdbc:sqlserver://192.168.1.114:1533;databaseName=qintech_db;integratedSecurity=true;
#spring.datasource.url=jdbc:sqlserver://192.168.1.114:1533;databaseName=qintech_db;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.username= user
#spring.datasource.password= Password13461
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework=TRACE
#logging.level.com.allintech=TRACE
#logging.level.root=DEBUG

#spring.cache
spring.cache.type=none
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false

#kiosk-backend port-https
#server.port=8443
#server.ssl.key-store=file:keystore.p12
#server.ssl.key-store-password=123456
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=1
#server.ssl.enabled=true

#logging
logging.file.path=/
logging.file.name=../../../../../../../Temp/qintechapi/logs.txt
logging.level.root=DEBUG
logging.level.org.hibernate=ERROR

#redis
spring.data.redis.host=192.168.1.108
spring.data.redis.port=6379
spring.data.redis.timeout=2000

#kiosk ui sunucu ip adresi olacak
kiosk.ui.ip=192.168.1.102

#kiosk health check schedule (cron expression)
kiosk.health.check.cron=0 10 10,12,16 * * ?

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

server.error.include-stacktrace=never
spring.web.resources.add-mappings=false
